title: Worry Bead Records
description: Independent record label from Queens, New York
url: "https://fennmacon.github.io"
baseurl: "/worrybead"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Collections
collections:
  news:
    output: false
    sort_by: date
  releases:
    output: false
    sort_by: date
  videos:
    output: false
    sort_by: date
  press:
    output: false
    sort_by: date

# Default front matter
defaults:
  - scope:
      path: ""
      type: "news"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "releases"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "videos"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "press"
    values:
      layout: "default"

# GitHub Pages compatible plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing
exclude:
  - README.md
  - update-guide.md
  - .DS_Store
  - Gemfile
  - Gemfile.lock
  - vendor/ 