[build]
  command = "bundle install && bundle exec jekyll build"
  publish = "_site"

[build.environment]
  RUBY_VERSION = "3.1.0"
  NODE_VERSION = "18"

[context.production]
  command = "bundle install && bundle exec jekyll build" 