[build]
  publish = "_site"
  command = "bundle exec jekyll build"

[build.environment]
  RUBY_VERSION = "3.1"

# Redirect rules for clean URLs
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff" 