backend:
  name: git-gateway
  branch: main

media_folder: "img"
public_folder: "/img"

collections:
  - name: "news"
    label: "News"
    folder: "_news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "Excerpt", name: "excerpt", widget: "text", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Link URL", name: "link", widget: "string", required: false}
      - {label: "Link Text", name: "link_text", widget: "string", default: "Read More"}

  - name: "releases"
    label: "Releases"
    folder: "_releases"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Artist", name: "artist", widget: "string"}
      - {label: "Release Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Bandcamp Embed URL", name: "bandcamp_embed", widget: "string", required: false}
      - {label: "Bandcamp Link", name: "bandcamp_link", widget: "string", required: false}

  - name: "videos"
    label: "Videos"
    folder: "_videos"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "YouTube Video ID", name: "youtube_id", widget: "string", required: false, hint: "Just the ID part from YouTube URL (e.g., 'dQw4w9WgXcQ')"}
      - {label: "Interactive Link", name: "interactive_link", widget: "string", required: false}

  - name: "press"
    label: "Press"
    folder: "_press"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Publication", name: "publication", widget: "string"}
      - {label: "Article Title", name: "title", widget: "string"}
      - {label: "URL", name: "link", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}

  - name: "settings"
    label: "Site Settings"
    files:
      - label: "About Page"
        name: "about"
        file: "_data/about.yml"
        fields:
          - {label: "Content", name: "content", widget: "markdown"}
      - label: "Contact Info"
        name: "contact"
        file: "_data/contact.yml"
        fields:
          - {label: "Content", name: "content", widget: "markdown"} 